name: env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit
  - pip:
    - absl-py==1.3.0
    - aiohttp==3.8.3
    - aiosignal==1.3.1
    - antlr4-python3-runtime==4.9.3
    - asttokens==2.2.1
    - async-timeout==4.0.2
    - attrs==22.1.0
    - awscli==1.27.26
    - backcall==0.2.0
    - bagua-cuda116==0.9.1
    - boto3==1.26.26
    - botocore==1.29.26
    - cachetools==5.2.0
    - colorama==0.4.4
    - contextvars==2.4
    - decorator==5.1.1
    - deprecation==2.1.0
    - docutils==0.16
    - einops==0.6.0
    - exceptiongroup==1.0.4
    - executing==1.2.0
    - fairscale==0.4.12
    - filelock==3.8.2
    - fire==0.4.0
    - flask==2.2.2
    - frozenlist==1.3.3
    - fsspec==2022.11.0
    - fvcore==0.1.5.post20221122
    - gevent==22.10.2
    - google-auth==2.15.0
    - google-auth-oauthlib==0.4.6
    - gorilla==0.4.0
    - greenlet==2.0.1
    - grpcio==1.51.1
    - h5py==3.7.0
    - hiddenlayer==0.3
    - huggingface-hub==0.11.1
    - immutables==0.19
    - importlib-metadata==5.1.0
    - iniconfig==1.1.1
    - iopath==0.1.10
    - ipython==8.10.0
    - itsdangerous==2.1.2
    - javalang==0.13.0
    - jedi==0.18.2
    - jinja2==3.1.2
    - jmespath==1.0.1
    - jsonlines==3.1.0
    - lightning-utilities==0.3.0
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib-inline==0.1.6
    - multidict==6.0.3
    - networkx==2.8.8
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - oauthlib==3.2.2
    - omegaconf==2.3.0
    - parallel-ssh==2.9.1
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pluggy==1.0.0
    - portalocker==2.6.0
    - prometheus-client==0.15.0
    - prompt-toolkit==3.0.37
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - py-cpuinfo==9.0.0
    - pyarrow==10.0.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydantic==1.10.2
    - pygments==2.14.0
    - pympler==1.0.1
    - pytest==7.2.0
    - pytest-benchmark==4.0.0
    - pytorch-lightning==1.8.3.post1
    - regex==2022.10.31
    - requests-oauthlib==1.3.1
    - rsa==4.7.2
    - s3transfer==0.6.0
    - scikit-learn==1.0.1
    - scikit-optimize==0.9.0
    - semantic-version==2.10.0
    - setuptools-rust==1.5.2
    - ssh-python==1.0.0
    - ssh2-python==1.0.0
    - stack-data==0.6.2
    - subseasonal-data==0.0.5
    - tabulate==0.9.0
    - tensorboard==2.11.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.5.1
    - termcolor==2.1.1
    - timm==0.6.12
    - tokenizers==0.13.2
    - tomli==2.0.1
    - torchsampler==0.1.2
    - torchviz==0.0.2
    - traitlets==5.9.0
    - transformers==4.25.1
    - unidiff==0.7.4
    - wcwidth==0.2.6
    - werkzeug==2.2.2
    - xxhash==3.1.0
    - yacs==0.1.8
    - yarl==1.8.2
    - zipp==3.11.0
    - zope-event==4.5.0
    - zope-interface==5.5.2
