layout:
  layout: "NTHWC"

data:
  data_dirs:
      mediteranean:
        tp: '/home/egauillard/data/PR_era5_MED_1degr_19400101_20240229_new.nc'
        t2m: "/home/egauillard/data/T2M_era5_MED_1degr_19400101-20240229.nc"
      north_hemisphere: 
        msl:  "/home/egauillard/data/MSLP_era5_NHExt_1degr_19400101_20240229_new.nc"
        sst: "/home/egauillard/data/SST_era5_NHExt_1degr_19400101-20240229_new.nc"
        stream: "/home/egauillard/data/STREAM500_era5_NHExt_1degr_19400101_20240229_new.nc"
      tropics:
        ttr: "/home/egauillard/data/OLR_era5_tropics_1degr_19400101_20240229.nc"
  dataset:
    variables_nh: ["stream", "sst", "msl"]
    variables_tropics: ['ttr']
    variables_med: ['tp', 't2m']
    target_variables: ['tp']
    relevant_years: [1940,2005]
    relevant_months: [9,10, 11, 12, 1, 2, 3]
    scaling_years: [1940,2005]
    land_sea_mask: '/home/egauillard/data/ERA5_land_sea_mask_1deg.nc'
    spatial_resolution: 1
    predict_sea_land: false 
    out_spatial_resolution: 1
    sum_pr: True
    coarse_t : true
    coarse_s : false
    coarse_s_target: false
    coarse_t_target: true
  scaler:
    mode: 'standardize'
  temporal_aggregator:
    in_len: 8
    out_len: 4
    resolution_input: 7
    resolution_output: 7
    gap: 4
    lead_time_gap: 0

model:
  season_float: false
  base_units: 64
  block_units: null
  scale_alpha: 1.0
  enc_depth: [1, 1]
  dec_depth: [1, 1]
  enc_use_inter_ffn: true
  dec_use_inter_ffn: true
  dec_hierarchical_pos_embed: true
  downsample: 2
  downsample_type: "patch_merge"
  upsample_type: "upsample"
  num_global_vectors: 8
  use_dec_self_global: true
  dec_self_update_global: true
  use_dec_cross_global: true
  use_global_vector_ffn: true
  use_global_self_attn: true
  separate_global_qkv: false
  global_dim_ratio: 1
  self_pattern: "axial"
  cross_self_pattern: "axial"
  cross_pattern: "cross_1x1"
  dec_cross_last_n_frames: null
  attn_drop: 0.1
  proj_drop: 0.1
  ffn_drop: 0.1
  num_heads: 4
  ffn_activation: "gelu"
  gated_ffn: false
  norm_layer: "layer_norm"
  padding_type: "zeros"
  pos_embed_type: "t+h+w"
  use_relative_pos: true
  self_attn_use_final_proj: true
  dec_use_first_self_attn: false
  z_init_method: "zeros"
  initial_downsample_type: "conv"
  initial_downsample_activation: "leaky"
  initial_downsample_scale: [1, 1, 2]
  initial_downsample_conv_layers: 2
  final_upsample_conv_layers: 1
  checkpoint_level: 2
  attn_linear_init_mode: "0"
  ffn_linear_init_mode: "0"
  conv_init_mode: "0"
  down_up_linear_init_mode: "0"
  norm_init_mode: "0"

optim:
  seed: 4
  total_batch_size: 64
  micro_batch_size: 8
  method: "adamw"
  lr: 0.0001
  wd: 0.001
  gradient_clip_val: 1.0
  max_epochs: 100
  warmup_percentage: 0.2
  lr_scheduler_mode: "cosine"
  min_lr_ratio: 0.1
  warmup_min_lr_ratio: 0.1
  early_stop: True
  early_stop_mode: "min"
  early_stop_patience: 10
  save_top_k: 3

logging:
  logging_prefix: "earthformer_mediteranean"
  monitor_lr: true
  monitor_device: false
  track_grad_norm: -1

trainer:
  check_val_every_n_epoch: 1
  log_step_ratio: 0.001
  precision: 32

vis:
  train_example_data_idx_list: [0]
  val_example_data_idx_list: [0]
  test_example_data_idx_list: [0]
  eval_example_only: false

