layout:
  in_len: 12
  out_len: 14
  img_height: 24
  img_width: 48
  layout: "NTHWC"

optim:
  method: "adamw"
  lr: 1E-3
  wd: 1E-5
  max_epochs: 50
  warmup_percentage: 0.2
  lr_scheduler_mode: "cosine"
  min_lr_ratio: 0.1

logging:
  logging_prefix: "ICAR_ENSO"

trainer:
  check_val_every_n_epoch: 1
  log_step_ratio: 0.001
  precision: 32

vis:
  train_example_data_idx_list: [0]
  val_example_data_idx_list: [0]
  test_example_data_idx_list: [0]
  eval_example_only: false

model:
  data_channels: 4
  input_shape: !!python/tuple [12, 24, 48, 4]
  target_shape: !!python/tuple [14, 24, 48, 4]
